server:
  port: 8000
  error:
    include-message: always
    include-exception: true
  servlet:
    session:
      timeout: 2592000
  tomcat:
    uri-encoding: UTF-8
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /static/**
  datasource:
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
